-- Todos los distritos de Lima Metropolitana (habilitados) y del Callao (deshabilitados).
-- Se puede ejecutar más de una vez: si el distrito ya existe, solo actualiza si está habilitado.
insert into public.distritos (nombre, habilitado) values
  ('Ancón', true),
  ('Ate', true),
  ('Barranco', true),
  ('Breña', true),
  ('Carabayllo', true),
  ('Chaclacayo', true),
  ('Chorrillos', true),
  ('Cieneguilla', true),
  ('Comas', true),
  ('El Agustino', true),
  ('Independencia', true),
  ('Jesús María', true),
  ('La Molina', true),
  ('La Victoria', true),
  ('Lima', true),
  ('Lince', true),
  ('Los Olivos', true),
  ('Lurigancho', true),
  ('Lurín', true),
  ('Magdalena', true),
  ('Miraflores', true),
  ('Pachacámac', true),
  ('Pucusana', true),
  ('Pueblo Libre', true),
  ('Puente Piedra', true),
  ('Punta Hermosa', true),
  ('Punta Negra', true),
  ('Rímac', true),
  ('San Bartolo', true),
  ('San Borja', true),
  ('San Isidro', true),
  ('San Juan de Lurigancho', true),
  ('San Juan de Miraflores', true),
  ('San Luis', true),
  ('San Martín de Porres', true),
  ('San Miguel', true),
  ('Santa Anita', true),
  ('Santa María del Mar', true),
  ('Santa Rosa', true),
  ('Surco', true),
  ('Surquillo', true),
  ('Villa El Salvador', true),
  ('Villa María del Triunfo', true),
  ('Callao', false),
  ('Bellavista', false),
  ('Carmen de la Legua', false),
  ('La Perla', false),
  ('La Punta', false),
  ('Mi Perú', false),
  ('Ventanilla', false)
on conflict (nombre) do update set habilitado = excluded.habilitado;
